# Back to "new user" state. Run from the project folder: .\teardown.ps1
# Reverse: npm install -g . ; alfred sync

Set-Location $PSScriptRoot

# junctions (rmdir removes the link only, never the target)
cmd /c rmdir "$env:USERPROFILE\.claude\skills\alfred"
cmd /c rmdir "$env:USERPROFILE\.copilot\installed-plugins\alfred\alfred"

# copilot registration (this also drops the plugin entry)
copilot plugin marketplace remove alfred

# global command
npm uninstall -g alfred-cli

# generated files (all gitignored, regenerated by sync)
Remove-Item -Recurse -Force plugin, logs, config\skills-index.json -ErrorAction SilentlyContinue
