#!/usr/bin/env bash
# Back to "new user" state on macOS / Linux. Run from anywhere: ./teardown.sh
# Reverse: npm install -g . && alfred sync
# Windows equivalent: teardown.ps1
#
# Removes only what `alfred sync` created. Every link is checked to be a symlink
# before removal, so a real folder that happens to sit at one of these paths is
# never deleted. Links first, so nothing can recurse into the real plugin/ folder.

set -u
cd "$(dirname "${BASH_SOURCE[0]}")"

PLUGIN_DIR="$PWD/plugin"

# Remove a path only if it is a symlink. rm on a symlink removes the link, never the target.
unlink_if_link() {
  if [ -L "$1" ]; then
    rm "$1" && echo "removed link   $1"
  elif [ -e "$1" ]; then
    echo "left alone     $1 (not a symlink; not created by alfred sync)"
  fi
}

echo "== links"
unlink_if_link "$HOME/.claude/skills/alfred"
unlink_if_link "$HOME/.copilot/installed-plugins/alfred/alfred"

# codex: one link per skill in ~/.agents/skills, a root shared with other tools.
# Only remove links that resolve back into this repo's plugin/skills/.
if [ -d "$HOME/.agents/skills" ]; then
  for link in "$HOME/.agents/skills"/alfred-*; do
    [ -L "$link" ] || continue
    target="$(readlink "$link")"
    case "$target" in
      "$PLUGIN_DIR"/skills/*) rm "$link" && echo "removed link   $link" ;;
      *) echo "left alone     $link (points outside this repo)" ;;
    esac
  done
fi

echo "== copilot registration (also drops the plugin entry)"
if command -v copilot >/dev/null 2>&1; then
  copilot plugin marketplace remove alfred 2>&1 | sed 's/^/  /' || true
else
  echo "  copilot CLI not on PATH, nothing registered to remove"
fi

echo "== global command"
npm uninstall -g alfred-cli 2>&1 | sed 's/^/  /'

echo "== generated files (gitignored, regenerated by sync)"
rm -rf plugin logs config/skills-index.json && echo "  removed plugin/ logs/ config/skills-index.json"

echo
echo "Teardown done. Bring it back: npm install -g . && alfred sync"
