# Back to "new user" state. Run from the project folder: .\teardown.ps1
# Reverse: npm install -g . ; alfred sync

Set-Location $PSScriptRoot

# junctions (rmdir removes the link only, never the target)
cmd /c rmdir "$env:USERPROFILE\.claude\skills\alfred"
cmd /c rmdir "$env:USERPROFILE\.copilot\installed-plugins\alfred\alfred"

# codex: one link per skill in ~/.agents/skills, a root shared with other tools.
# Only ever remove reparse points (links); a real folder there is someone else's skill.
Get-ChildItem "$env:USERPROFILE\.agents\skills" -Filter 'alfred-*' -Directory -ErrorAction SilentlyContinue |
  Where-Object { $_.Attributes -band [IO.FileAttributes]::ReparsePoint } |
  ForEach-Object { cmd /c rmdir "$($_.FullName)" }

# copilot registration (this also drops the plugin entry)
copilot plugin marketplace remove alfred

# global command
npm uninstall -g alfred-cli

# generated files (all gitignored, regenerated by sync)
Remove-Item -Recurse -Force plugin, logs, config\skills-index.json -ErrorAction SilentlyContinue
