'use strict';

const fs = require('fs');
const path = require('path');
const PATHS = require('./paths');
const { parseFrontmatter } = require('./frontmatter');
const { buildIndex } = require('./skillsIndex');

// Shape both Claude Code and Copilot read from:
// plugin/.claude-plugin/plugin.json + plugin/skills/<name>/SKILL.md. One build feeds every tool.

function generatePluginJson() {
  const pkg = require(path.join(PATHS.root, 'package.json'));
  const manifest = {
    name: 'alfred',
    displayName: 'Alfred',
    version: pkg.version,
    description: pkg.description,
  };
  const dir = path.join(PATHS.plugin, '.claude-plugin');
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'plugin.json'), JSON.stringify(manifest, null, 2));
}

// Rebuilt from scratch every time, so deleted skills disappear from every tool.
function syncSkills(skills) {
  const outRoot = path.join(PATHS.plugin, 'skills');
  fs.rmSync(outRoot, { recursive: true, force: true });
  fs.mkdirSync(outRoot, { recursive: true });

  for (const skill of skills) {
    const skillDir = path.join(outRoot, skill.name);
    fs.mkdirSync(skillDir, { recursive: true });
    const raw = fs.readFileSync(skill.path, 'utf8');
    const { body } = parseFrontmatter(raw);
    const header = raw.slice(0, raw.length - body.length);
    const startup = skill.memory === false ? '' : memoryStartup(skill.name);
    fs.writeFileSync(path.join(skillDir, 'SKILL.md'), header + startup + body);
  }
}

// Throws if any skill is invalid; nothing is written to plugin/ in that case.
function buildPlugin() {
  const skills = buildIndex();
  fs.mkdirSync(PATHS.plugin, { recursive: true });
  generatePluginJson();
  syncSkills(skills);
  fs.mkdirSync(PATHS.memory, { recursive: true });
  const global = path.join(PATHS.memory, 'global.md');
  if (!fs.existsSync(global)) fs.writeFileSync(global, '# Global memory\n', { flag: 'wx' });
  return skills.length;
}

function memoryStartup(name) {
  const cli = path.join(PATHS.root, 'bin', 'alfred.js').replace(/\\/g, '/');
  return `\n<!-- Generated by Alfred; edit the source skill, not this block. -->
## Alfred memory startup

Before doing this skill's work, load its shared memory. If a native hook has already
provided an "Alfred memory ready: ${name}" receipt for THIS invocation, use that
context and skip the command. A receipt from an earlier use is not a new invocation.
Otherwise run the following using your shell tool from the user's working directory:

    node "${cli}" memory start --skill ${name} --tool <tool>

Replace <tool> with claude, copilot, or codex according to the host running you.
If this conversation already has an Alfred session ID, add --session "<that ID>".
Otherwise reuse the new ID returned by this call for all later skills. If you know
the native session ID, use it. Do not use another conversation's ID or invent a fixed ID.
For a retry of the same invocation, add the same --event "<unique invocation ID>".
Read the returned context and follow its write-back contract before your final answer.
Do not change directory to the Alfred install. An inactive/failed memory startup must
not block the skill. Report an actual error briefly; respect host permissions.

<!-- End generated startup. -->\n\n`;
}

module.exports = { buildPlugin, memoryStartup };
